In [1]:
import numpy as np

### Array filled with 0's : Zeros Array

In [2]:
ar_zero_1 = np.zeros(4)
print(ar_zero_1)
print(ar_zero_1.ndim)

print()

ar_zero_2 = np.zeros((3,4))
print(ar_zero_2)
print(ar_zero_2.ndim)

[0. 0. 0. 0.]
1

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


### Array filled with 1's : Ones Array

In [3]:
ar_one_1 = np.ones(5)
print(ar_one_1)

ar_one_2 = np.ones((2,3))
print(ar_one_2)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


### Elements with a particular range of numbers

In [4]:
arr_1 = np.arange(4)
print(arr_1)

arr_2 = np.arange(1,9,2)
print(arr_2)

arr_3 = np.arange(10,0,-1)
print(arr_3)


[0 1 2 3]
[1 3 5 7]
[10  9  8  7  6  5  4  3  2  1]


### rand() function : Generate array with random values b/w 0 and 1

In [5]:
arr_4 = np.random.rand(4) 
print(arr_4)

arr_5 = np.random.rand(4,5)
print(arr_5)

[0.28190664 0.52749447 0.9305384  0.24947574]
[[0.41384938 0.94838864 0.67761486 0.79397685 0.24638587]
 [0.02941366 0.29167238 0.801569   0.32123428 0.96334712]
 [0.15991931 0.25140754 0.85328266 0.3548833  0.56941291]
 [0.66775534 0.71956075 0.29707147 0.52238462 0.06763961]]


### randn() function: Generate array with random values that are close to 0. They may be +ve and -ve

In [6]:
arr_6 = np.random.randn(5)
print(arr_6)

arr_7 = np.random.randn(2,3)
print(arr_7)

[ 1.32724123  1.31989063 -0.45529069 -1.2355807   0.39427883]
[[ 0.74876209 -0.06920235 -1.02398983]
 [-0.04396444  0.72285764 -0.55414008]]


### ranf() function : Similar to rand() function but here range is [0.0, 1.0)

In [7]:
arr_8 = np.random.ranf(4)
print(arr_8)

arr_9 = np.random.ranf((2,7))
print(arr_9)


[0.03574397 0.62620668 0.58359093 0.85436377]
[[0.00994844 0.64903554 0.61757283 0.9915451  0.10865014 0.29130103
  0.65891713]
 [0.70061073 0.91143464 0.36990356 0.59066835 0.80440654 0.8486895
  0.37159807]]


### randint() function : Generates random number within a given range

In [8]:
# var = np.random.randint(min, max, shape) =>  This is the syntax

var_1 = np.random.randint(1,9,5)
print(var_1)

var_2 = np.random.randint(1,9,(2,5))
print(var_2)
print(var_2.shape)

[1 7 7 5 6]
[[8 6 1 5 1]
 [5 6 4 1 8]]
(2, 5)
