### Data Type
The dtype attribute for an array returns the data type of that array, every element in that array belongs to that data type

In [2]:
import numpy as np

In [5]:
var = np.array([1,2,3,4,5,6,7, 8.0])
print("Data Type:",var.dtype)

Data Type: float64


In [6]:
var1 = np.array(["A","B","C","D"])
print("Data Type:",var1.dtype)

Data Type: <U1


In [8]:
var2 = np.array(["A", "B", 1.0])
print("Data Type:",var2.dtype)

Data Type: <U32


### Conversion of Data Type

In [29]:
x = np.array([1,2,3,4], dtype=np.int32)
print(x.dtype)
print(x)


int32
[1 2 3 4]


In [31]:
y = np.array([4,5,6,7,8], dtype="f")
print(y.dtype)
print(y)

new = np.int32(y)
print(new.dtype)
print(new)

float32
[4. 5. 6. 7. 8.]
int32
[4 5 6 7 8]
