### Arithmetic Operations

In [16]:
import numpy as np

In [17]:
var = np.array([1,2,3,4])
varadd = var + 3 #Adding 3 to every element of the array
# varadd = np.add(var,3)
print(varadd)

[4 5 6 7]


In [18]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])

print(np.add(var1, var2))

[ 6  8 10 12]


In [19]:
# For 2D Array

var2d1 = np.array([[1,2,3],[4,5,6]])
var2d2 = np.array([[4,5,6],[1,2,3]])

print(var2d1)
print()
print(var2d2)
print()

print(np.add(var2d1, var2d2))
print()
print(np.subtract(var2d1, var2d2))
print()
print(np.multiply(var2d1, var2d2))
print()

[[1 2 3]
 [4 5 6]]

[[4 5 6]
 [1 2 3]]

[[5 7 9]
 [5 7 9]]

[[-3 -3 -3]
 [ 3  3  3]]

[[ 4 10 18]
 [ 4 10 18]]



### Max/Min element

In [20]:
a = np.array([1,2,3,4,5,6,8])
print("Minimum Element:", a.min(), ", Index:",a.argmin())
print("Maximum Element:", a.max(), ", Index:",a.argmax())

Minimum Element: 1 , Index: 0
Maximum Element: 8 , Index: 6


In [21]:
b = np.array([[4,2,1],[3,5,6]])

"""
For 1d array -> Row : Axis = 0

For 2d array -> Column : Axis = 0, Row : Axis = 1

For 3d array -> Column : Axis = 0, Row : Axis = 1, Width : Axis = 2
"""

print(b.min(axis=0), b.max(axis=0))
print(b.min(axis=1),b.max(axis=1))


[3 2 1] [4 5 6]
[1 3] [4 6]
