In [2]:
import numpy as np

In [3]:
var = np.array([[1,2,3],[3,4,5]])
print(var)
print(var.shape)
print(var.ndim)

[[1 2 3]
 [3 4 5]]
(2, 3)
2


In [9]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(a.shape)
print(a.ndim)

reshaped = a.reshape((3,3))
print(reshaped)
print(reshaped.shape)
print(reshaped.ndim)


[1 2 3 4 5 6 7 8 9]
(9,)
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


In [10]:
old = reshaped.reshape(-1)
print(old)
print(old.shape)
print(old.ndim)

[1 2 3 4 5 6 7 8 9]
(9,)
1
