In [1]:
import numpy as np

### Indexing -> From start indexing starts from 0, and from end indexing starts from -1

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0])


1


In [3]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[1,2])
print(b[1][2])

6
6


### Slicing -> [start : stop : step]

In [4]:
c = np.array([1,2,3,4,5,6,7,8,9])
print(c[1:-2:2])

[2 4 6]


In [12]:
d = np.array([[1,2,3,4],[7,8,9,10],[11,12,13,14]])
# print(d)
print(d[0,::-1])
print(d[1,1:])

[4 3 2 1]
[ 8  9 10]
