In [1]:
import numpy as np

#### Search Array

In [6]:
arr = np.array([1,2,3,4,2,5,2,5,6,7])
x = np.where(arr == 2) #This will return an array
print(x)

y = np.where(arr%2 == 0)
print(y)

z = np.where(arr%2 != 0)
print(z)

(array([1, 4, 6]),)
(array([1, 3, 4, 6, 8]),)
(array([0, 2, 5, 7, 9]),)


#### Shuffle 


In [23]:
var = np.array([1,2,3,4,5,6])
np.random.shuffle(var) #It modifies the original array
print(var)

[3 5 6 4 1 2]


#### Unique

In [26]:
var1 = np.array([1,2,3,4,2,5,6,2,7])
res = np.unique(var1, return_index = True, return_counts=True)
print(res)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 6, 8]), array([1, 3, 1, 1, 1, 1, 1]))


#### Resize
resize() modifies the number of elements in a NumPy array, potentially adding or removing elements. reshape() changes the shape of the array without altering the number of elements.

In [31]:
var2 = np.array([1,2,3,4,5,6])
y = np.resize(var2,(4,4))
y

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])